### ISSUE TITLE
Barra receive progress

### ISSUE THREAD

**Issue by robyanne92** [robyanne92/piantapannocchie#29]
Quando si stabilisce la connessione compare la barra receiveprogress senza motivo. Controllare il perchè.

**Comment by robyanne92** [comment]
Il problema si verfica solo se a connettersi è Aramis.

**Comment by robyanne92** [comment]
@giansimo tu per caso apri subito il canale per il trasferimento files quando si stabilisce la connessione? Perchè in realtà andrebbe aperto solo nel momento in cui si deve inviare un file, e va chiuso subito dopo che tutti i bytes sono stati trasferiti.

**Comment by robyanne92** [comment]
Nel caso di aramis, che non credo preveda la possibilità di inviare files, il canale non deve essere aperto. Ci pensa il listener ad aprirlo quando deve inviare un file. Se aramis apre il canale, sul web compare la barra receiveProgress perchè pensa che stia arrivando un file :grin:

**Comment by giansimo** [comment]
Yep...ora risolvo!
