### ISSUE TITLE
Nascondere alcuni tasti per disegnare in certi casi

### ISSUE THREAD

**Issue by ChristianBar** [robyanne92/piantapannocchie#3]
- Se lo streamer è la webapp, il modo e l'offset vanno nascosti
- Se il modo è 2D o Collider, l'offset va nascosto

**Comment by ChristianBar** [comment]
sembra che il problema non sia ancora risolto, verificare che lo scambio di messaggi SET_STREAMER_PLATFORM nei vari casi e che il sito si comporti correttamente

**Comment by robyanne92** [comment]
Ho fatto un po' di test con l'ultima versione di Aramis su s9... Funziona tutto regolarmente, il sito mostra l'opzione set mode ed eventualmente anche set offset.

**Comment by ChristianBar** [comment]
allora chiudiamola sta issue, anche a me funzionava... se poi a massimo ancora non va cerchiamo di capire meglio cosa fa lui per non farlo funzionare
