### ISSUE TITLE
aggiunta modalità fullScreen

### ISSUE THREAD

**Issue by AlysMu** [robyanne92/piantapannocchie#30]
![fullScreen01](https://user-images.githubusercontent.com/48628158/77078678-35e10780-69f7-11ea-869e-480b8ddffe50.png)
![fullScreen02](https://user-images.githubusercontent.com/48628158/77078691-38dbf800-69f7-11ea-8b54-5717027db497.png)

**Comment by robyanne92** [comment]
Tutto bello ma non hai committato l'icona del fullscreen :)

**Comment by ChristianBar** [comment]
vero manca l'immaginetta del fullscreen nel commit ;P
