### ISSUE TITLE
Connettività Listen-Streamer

### ISSUE THREAD

**Issue by tarrogen** [robyanne92/piantapannocchie#31]
- Verifica connettività in caso di caduta connessione (down di rete, webserver, browser in cui NON vi sia notifica) 
- Ritentare la riconnessione solo se le risorse sono attive .
- Indicazione (led) che lo streamer mobile sia connesso al server ICE e pronto ad erogare il servizio
- Pulizia in caso di crash di tutte le istanze locali ... Non avere la possibilità di avere più istanze sullo stesso mobile
- Farsi che il server ICE sia aggiornato sulle registrazione presenti in modo continuativo: ossia previa prima auth alla connessione, verificare nel tempo che questa sia ancora attiva.
- Disabilitare durante la chiamata remota il salvaschermo sul mobile.
- Eventi sonori nel cambio di stato della connessione

**Comment by robyanne92** [comment]
Ho fatto una prova per vedere come si comporta la connessione in caso di down della rete. Nel momento in cui manca la rete, la iceconnection passa a "disconnected", nel metodo evidenziato in figura. @giansimo al posto del keepalive che mi dicevi potremmo provare ad usare questa variabile per segnalare all'utente che non si è più connessi.

![image](https://user-images.githubusercontent.com/53224473/77319545-4bb03e80-6d0f-11ea-8f46-0cdd84c00619.png)

**Comment by giansimo** [comment]
Lato streamer va comunque gestito il caso di riconnessione automatica...provo a fare uno studio di tutti i vari casi così valutiamo bene come si può procedere cercando di ridurre al minimo le modifiche

**Comment by giansimo** [comment]
Di seguito alcuni test effettuati organizzati per Peer ed in base al motivo di una possibile caduta della connessione:

**Test lato listener**

Caso di chiusura forzata della finestra del sito web o del browser.
- Arriva correttamente l'unregister sul server ICE
- lo streamer riceve lo stato di DISCONNECTED sull icepeerconnectionstate dopo qualche secondo e poi va in FAILED
- lo streamer riceve l'evento di peerleft grazie al socket con l'ice

Caso di down della rete 
- lo streamer riceve lo stato di DISCONNECTED sull icepeerconnectionstate dopo qualche secondo e poi va in FAILED

**Test lato streamer**

Caso di chiusura forzata dell'app
- Arriva corretamente l'unregister sul server ICE
- il listener riceve gli eventi EVENT_PEER_LEFT e EVENT_STREAMER_LEFT
- il listener NON riceve lo stato di DISCONNECTED sull'icepeerconnectionstate

Caso di down della rete
- il listener riceve lo stato di DISCONNECTED sull'icepeerconnectionstate
- il listener riceve gli eventi EVENT_PEER_LEFT e EVENT_STREAMER_LEFT

**Test multipli
2 listener e 1 streamer**

Caso di chiusura forzata dell'app
- Arriva corretamente l'unregister sul server ICE
- il listener in connessione non riceve lo stato di DISCONNECTED sull'icepeerconnectionstate
- il listener in connessione riceve l'evento EVENT_PEER_LEFT e EVENT_STREAMER_LEFT
- il listener in attesa riceve solo l'evento EVENT_STREAMER_LEFT

Caso di down della rete
- il listener in connessione riceve lo stato di DISCONNECTED sull'icepeerconnectionstate
- il listener in connessione riceve gli eventi EVENT_PEER_LEFT e EVENT_STREAMER_LEFT
- il listener in attesa riceve solo l'evento EVENT_STREAMER_LEFT

**2 streamer e 1 listener (simulazione 1 streamer app e 1 streamer browser)**

Caso di chiusura forzata dell'app
- Arriva corretamente l'unregister sul server ICE
- il listener in connessione non riceve lo stato di DISCONNECTED sull'icepeerconnectionstate
- il listener in connessione riceve l'evento EVENT_PEER_LEFT e EVENT_STREAMER_LEFT
- lo streamer in attesa non riceve nessun evento

Caso di down della rete
- il listener in connessione riceve lo stato di DISCONNECTED sull'icepeerconnectionstate
- il listener in connessione riceve gli eventi EVENT_PEER_LEFT e EVENT_STREAMER_LEFT
- lo streamer in attesa non riceve nessun evento

**Comment by robyanne92** [comment]
@giansimo prova a vedere come va ora lato web se va giù il server ice... dovrebbero disconnettersi correttamente.
