### ISSUE TITLE
CHAT lato listen unidirezionale

### ISSUE THREAD

**Issue by tarrogen** [robyanne92/piantapannocchie#32]
Lo streamer riceve i messaggi di chat ma NON riesce a rispondere, o meglio lato stream NON si vedono arrivare

**Comment by robyanne92** [comment]
parliamo di comunicazione web-web? Sto usando la chat e mi sembra funzionare, sia per il listener che per lo streamer.

![image](https://user-images.githubusercontent.com/53224473/77089034-95461400-6a05-11ea-86e7-eec86d2865ff.png)

**Comment by robyanne92** [comment]
"abbatti la connessione lato listen e poi la riattivi vedi che la chat è unidrezionale".

Ok confermo, bug da risolvere.

**Comment by robyanne92** [comment]
A seguito della risoluzione di questo bug ho dovuto modificare leggermente l'iter di creazione del datachannel. Adesso funziona così:

- il listener crea un datachannel richiamando la funzione createdatachannel
- questo attiva la funzione ondatachannel sullo streamer, il quale salva il datachannel in una variabile e lo userà per inviare messaggi.

Prima le cose erano diverse, in quanto anche lo streamer creava un datachannel tramite createdatachannel (anche se con lo stesso nome, ma creava comunque un canale differente dal primo),

@giansimo occorre per cui fare una piccola modifica al plugin, ma non la voglio fare io perchè non ho poi modo di testarlo. In pratica le modifiche dovrebbero essere:
- nella classe PeerConnectionStreamer.java, commentare o eliminare riga 256 (quella che crea il data channel).
- nella funzione onDataChannel (riga 423), dopo l'if a riga 426 aggiungere mDataChannel = dataChannel. In questo modo anche lo streamer ha come riferimento lo stesso datachannel del listener.

**Comment by giansimo** [comment]
Dopo le modifiche la comunicazione continua ad avvenire in maniera corretta...!
