### ISSUE TITLE
Problemucci grafica chat quando lo streamer è aramis

### ISSUE THREAD

**Issue by ChristianBar** [robyanne92/piantapannocchie#33]
Se lo streamer è aramis:
- dovrebbe essere reso più chiaro che la chat non è disponibile ma l'invio dei file si
- la scritta "textual chat not compatible with" sembra piazzata sopra (e forse non è completa)
- la barra receiving progress non si dovrebbe vedere
- tutto quello spazio vuoto è superfluo

![Annotazione 2020-03-20 111412](https://user-images.githubusercontent.com/13584964/77154420-f0c2e100-6a9b-11ea-8b2f-c490105412b7.jpg)

**Comment by robyanne92** [comment]
- per come è strutturata la chat non mi vengono molte idee per risaltare l'invio file. Forse in questo caso sarebbe meglio togliere l'invio file dalla chat e metterlo come finestra a se stante (anche se così non mi dispiaceva). Oppure si potrebbe mettere un messaggio nella finestra dedicata allo scambio messaggi (ad esempio compare come un messaggio inviato da remoto, quindi bianco sulla destra. "la chat non è disponibile ma è possibile inviare file").
- è un attributo placeholder della textinput, ma essendo piccola la finestra non si legge tutta la scritta subito ma bisogna scrollare. In alternativa si potrebbe fare come il punto sopra.
- risolto da Gianpaolo, era il bug https://github.com/robyanne92/piantapannocchie/issues/29
- qui cedo la parola a @AlysMu

**Comment by robyanne92** [comment]
Pardon, ho chiuso per sbaglio.

**Comment by ChristianBar** [comment]
Fate voi in maniera che un utente ignorante capisca cosa può e non può fare, tutto lì... Non mi prendo il mal di pancia di decidere cos'è meglio :)

**Comment by robyanne92** [comment]
![image](https://user-images.githubusercontent.com/53224473/77165408-7ea9c680-6ab2-11ea-8fe7-566f2d42d929.png)

**Comment by ChristianBar** [comment]
👍 per me
