### ISSUE TITLE
Interfaccia utente solo in webrtc app

### ISSUE THREAD

**Issue by ChristianBar** [robyanne92/piantapannocchie#38]
L'interfaccina con il nome dell'utente connesso e il menu "logout/change password" andrebbe messo in tutte le sotto-webapp, e anche nella home...

**Comment by robyanne92** [comment]
E anche nella schermata di login :) @PaolaAtanasio

**Comment by AlysMu** [comment]
ma allora lasciarla solo nella home no?
in starterApp.
che senso ha metterla nella home e poi dentro le app?

**Comment by robyanne92** [comment]
io mi riferivo praticamente alla top bar (senza la voce preferences e switch to streamer/listener) che andrebbe messa in tutte le pagine...

**Comment by AlysMu** [comment]
ok, si si certo la top con il back per tornare alla home ovviamente va benissimo, mentre cito: " nome dell'utente connesso e il menu "logout/change password" " in ogni pagina app non va bene. mentrer messo solo nella home avrebbe più senso

**Comment by robyanne92** [comment]
Anche quello secondo me dovrebbe stare in tutte le pagine, fornisce le informazioni sulla sessione attiva e permette in qualunque momento di poter fare il logout. Se noti così è come fanno praticamente tutti i siti che prevedono una login (facebook e compagnia bella, forum vari ecc...)

**Comment by AlysMu** [comment]
con la stessa medesima topbar. allora oltre quelle fisse, non dovrebbero andarci altre impostazioni. se  seguiamo l'esempio dei siti. comunque ok.
